version: "2"
services:
  isc-dhcp:
    image: "networkboot/dhcpd"
    network_mode: host
    volumes:
    - /home/dr/dhcp/:/data/
  glass:
    image: "node:8"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - .:/home/node/app
      - /home/dr/dhcp:/var/lib/dhcp
      - /home/dr/dhcp/dhcpd.conf:/etc/dhcp/dhcpd.conf
      - /home/dr/dhcp/
    ports:
      - "8085:8080"
      - "8086:3000"
    command: "/bin/sh -c 'npm install npm@4 && npm install && npm start'"
